<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  /*   'Formulaire_User\Module'                        => __DIR__ . '/Module.php',
    'Formulaire_User\Controller\FormulaireController' => __DIR__ . '/src/Formulaire_User/Controller/FormulaireController.php',
    'Formulaire_UserTest\Framework\TestCase'        => __DIR__ . '/tests/Formulaire_User/Framework/TestCase.php',
    'Formulaire_UserTest\SampleTest'                => __DIR__ . '/tests/Formulaire_User/SampleTest.php', */
);
