<?php
$title = 'Ajout d\'un utilisateur';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', array(
    'action' => 'adduser'
)));
$form->prepare();

echo $this->form()->openTag($form);
?>
<table>
	<tr>
		<td><?php echo $this->formlabel($form->get('user_surname'))?></td>
		<td><?php echo $this->formelement($form->get('user_surname'))?></td>
		<td><?php echo $this->formelementerrors($form->get('user_surname'))?></td>
	</tr>
	<tr>
		<td><?php echo $this->formlabel($form->get('user_fisrt_name'))?></td>
		<td><?php echo $this->formelement($form->get('user_fisrt_name'))?></td>
		<td><?php echo $this->formelementerrors($form->get('user_fisrt_name'))?></td>
	</tr>
    <tr>
		<td><?php echo $this->formlabel($form->get('user_civility'))?></td>
		<td><?php echo $this->formelement($form->get('user_civility'))?></td>
		<td><?php echo $this->formelementerrors($form->get('user_civility'))?></td>
	</tr>
	<tr>
		<td><?php echo $this->formlabel($form->get('user_mail'))?></td>
		<td><?php echo $this->formelement($form->get('user_mail'))?></td>
		<td><?php echo $this->formelementerrors($form->get('user_mail'))?></td>
	</tr>
	<tr>
		<td><?php echo $this->formlabel($form->get('user_password'))?></td>
		<td><?php echo $this->formelement($form->get('user_password'))?></td>
		<td><?php echo $this->formelementerrors($form->get('user_password'))?></td>
	</tr>
	<tr>
		<td><?php echo $this->formlabel($form->get('user_password_confirm'))?></td>
		<td><?php echo $this->formelement($form->get('user_password_confirm'))?></td>
		<td><?php echo $this->formelementerrors($form->get('user_password_confirm'))?></td>
	</tr>	
</table>
<?php echo $this->formelement($form->get('submit'))?>

<?php

echo $this->form()->closeTag();
?>