<?php
$title = 'Liste des cients';
$this->headTitle($title);

?>

<h1><?php echo $this->escapeHtml($title);?></h1>
<p>
	<a
		href="
	<?php echo $this->url('customer', array('action'=>'addcustomer'));?>
 	">Ajouter un nouveau client</a>
</p>
<table class="table">
	<tr>
		<th>Nom</th>
		<th>Numéro de société</th>
		<th>Validation</th>
		<th>Numéro client</th>
		<th>Téléphone</th>
		<th>Fax</th>
		<th>Adresse</th>
		<th>CP</th>
		<th>Ville</th>
		<th>Pays</th>
		<th>Type</th>
		<th>&nbsp;</th>
	</tr>
<?php foreach ($customers as $customer): ?>
<tr>
		<td><?php echo $this->escapeHtml($customer->customer_name);?></td>
		<td><?php echo $this->escapeHtml($customer->customer_company_number);?></td>
		<td><?php echo $this->escapeHtml($customer->customer_validate);?></td>
		<td><?php echo $this->escapeHtml($customer->customer_number);?></td>
		<td><?php echo $this->escapeHtml($customer->customer_telephone);?></td>
		<td><?php echo $this->escapeHtml($customer->customer_fax);?></td>
		<td><?php echo $this->escapeHtml($customer->customer_address);?></td>
		<td><?php echo $this->escapeHtml($customer->customer_zipcode);?></td>
		<td><?php echo $this->escapeHtml($customer->customer_city);?></td>
		<td><?php echo $this->escapeHtml($customer->customer_country);?></td>
		<td><?php echo $this->escapeHtml($customer->customer_type);?></td>
		<td><a
			href="<?php echo $this->url('customer', array('action'=>'editcustomer','customer_id'=>$customer->customer_id));?>">Modifier</a>
			<a
			href="<?php echo $this->url('customer', array('action'=>'deletecustomer','customer_id'=>$customer->customer_id));?>">Supprimer</a>
		</td>
	</tr>
<?php endforeach;?>
</table>
