<div class="hero-unit">
	<h1><?php echo sprintf($this->translate('Bienvenu sur Agotte.com'), '<span class="zf-green">', '</span>') ?></h1>
	<br>
	<p>
		<a class="btn btn-success btn-large" href="/backoffice"><?php echo $this->translate('Accéder aux backoffices')?>
     &raquo;</a>
	</p>
</div>

<div class="row">

	<div class="span4"></div>

	<div class="span4"></div>

	<div class="span4"></div>
</div>
